apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-dotnet-deployment
  namespace: hello-dotnet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-dotnet
  template:
    metadata:
      labels:
        app: hello-dotnet
    spec:
      imagePullSecrets:
        - name: nexus-secret
      containers:
      - name: hello-dotnet
        image: 127.0.0.1:30085/my-repository/hello-dotnet:v001
        ports:
        - containerPort: 4567
---
apiVersion: v1
kind: Service
metadata:
  name: hello-dotnet-service
  namespace: hello-dotnet
spec:
  selector:
    app: hello-dotnet
  ports:
    - protocol: TCP
      port: 4567  # Service port
      targetPort: 4567  # Container port
  type: ClusterIP
